apiVersion: v1
kind: Pod
metadata:
  name: random-number-generator
spec:
  containers:
  - image: alpine
    name: alpine
    ##Create File
    # command: ["/bin/sh", "-c"]
    # args: ["shuf -i 0-100 -n 1 >> /opt/file.txt"]
    ##tty
    command: ["sh", "-c", "tail -f /dev/null"]
    volumeMounts:
    - mountPath: /opt
      name: data-volume
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: my-pv-claim