apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: training
spec:
  containers:
  - image: nginx
    name: nginx
  restartPolicy: Never
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "red"
    effect: "NoSchedule"
